// Generated by Haxe 4.0.0-preview.4+1e3e5e016
if (process.version < "v4.0.0") console.warn("Module " + (typeof(module) == "undefined" ? "" : module.filename) + " requires node.js version 4.0.0 or higher");
(function () { "use strict";
var $hxEnums = {};
var AgentScreen = require("agentscreen").AgentScreen;
var Go = function() { };
Go.main = function() {
	new Server();
};
var Server = function() {
	var _gthis = this;
	js_node_Http.createServer(function(req,res) {
		var q = req.url.split("/");
		q.shift();
		_gthis.action = q.shift();
		console.log("src/Server.hx:22:","action:" + _gthis.action);
		var _g = _gthis.action;
		switch(_g) {
		case "logout":
			_gthis.agentScreen.close();
			res.writeHead(200,{ "Content-Type" : "text/plain"});
			res.end("Goodbye\n");
			break;
		case "screenshot":
			res.writeHead(200,{ "Content-Type" : "image/jpeg"});
			_gthis.agentScreen.screenshot().then(function(shot) {
				res.end(shot);
			});
			break;
		case "start":
			var _g1 = new haxe_ds_StringMap();
			while(q.length > 0) {
				var key = q.shift();
				var value = q.shift();
				if(__map_reserved[key] != null) {
					_g1.setReserved(key,value);
				} else {
					_g1.h[key] = value;
				}
			}
			_gthis.param = _g1;
			_gthis.agentScreen = new AgentScreen("https://xpress.mein-dialer.com/agc/vicidial.fly-xpress.php?relogin=YES&VD_login=6666&VD_campaign=QCKINDER&phone_login=666&phone_pass=666ohne&VD_pass=dial4NICHTS");
			_gthis.agentScreen.run();
			res.writeHead(200,{ "Content-Type" : "text/plain"});
			res.end("Hello World\n");
			break;
		}
	}).listen(1337,"127.0.0.1");
	console.log("Server running at 1337");
};
var haxe_IMap = function() { };
var haxe_ds_StringMap = function() {
	this.h = { };
};
haxe_ds_StringMap.__interfaces__ = [haxe_IMap];
haxe_ds_StringMap.prototype = {
	setReserved: function(key,value) {
		if(this.rh == null) {
			this.rh = { };
		}
		this.rh["$" + key] = value;
	}
};
var haxe_io_Bytes = function(data) {
	this.length = data.byteLength;
	this.b = new Uint8Array(data);
	this.b.bufferValue = data;
	data.hxBytes = this;
	data.bytes = this.b;
};
var js_node_Http = require("http");
var __map_reserved = {};
Go.main();
})();
